# In this notebook, I will practice the following skills:
    * read multiple files in some specific folder

In [22]:
import os
import glob

import pandas as pd
import numpy as np

In [29]:
# Read files
# Ref: https://stackoverflow.com/questions/18262293/how-to-open-every-file-in-a-folder
# Ref: https://stackoverflow.com/questions/541390/extracting-extension-from-filename-in-python

df = pd.DataFrame()
for filefullpath in glob.glob('./data/points-separate*.csv'):
    
    # filefullpath = './data/points_separate_1.csv', ...
    fullfilename = os.path.basename(filefullpath)
    
    # fullfilename = 'points-separate_1.csv', ...
    filename, file_extension = os.path.splitext(fullfilename)
    
    # filename = 'points_separate_1', ...
    filename, sn = filename.split(sep='_')[0], filename.split(sep='_')[1]
    
    
    # read and concat the files
    df_read = pd.read_csv(filefullpath, sep=',')
    df_read['data_source'] = filename
    df_read['serial_number'] = sn
    df = pd.concat([df, df_read], axis=0)
    
df

                datetime    points      data_source serial_number
0    2000/01/05 23:21:12  0.562355  points-separate             1
1    2000/01/21 02:14:00  0.345169  points-separate             1
2    2000/02/05 05:06:48  0.321268  points-separate             1
3    2000/02/20 07:59:36  0.140051  points-separate             1
4    2000/03/06 10:52:24  0.685803  points-separate             1
..                   ...       ...              ...           ...
328  2027/05/03 04:09:12  0.201068  points-separate             2
329  2027/05/18 07:02:00  0.110429  points-separate             2
330  2027/06/02 09:54:48  0.223672  points-separate             2
331  2027/06/17 12:47:36  0.750551  points-separate             2
332  2027/07/02 15:40:24  0.620772  points-separate             2

[1000 rows x 4 columns]